export const DREAM_INPUT_MAX_LENGTH = 2000;

export const DREAM_COPY = {
  dari: {
    title: 'تعبیر خواب اسلامی',
    subtitle: 'بر اساس قرآن، حدیث و کتب اهل سنت',
    notConfigured: 'سرویس تعبیر خواب هنوز پیکربندی نشده است.',
    welcome: 'السلام علیکم. خواب خود را به زبان ساده برایم قصه کنید — چه دیدید و در خواب چه احساسی داشتید؟ ان‌شاءالله بر اساس قرآن، حدیث و کتب معتبر اهل سنت برای شما تعبیر می‌کنم.',
    placeholder: 'خواب خود را اینجا بنویسید…',
    newChat: 'گفتگوی جدید',
    chipsLabel: 'خواب‌های عام:',
    disclaimer: 'تعبیر خواب ظنی است؛ علم قطعی تنها نزد الله سبحانه و تعالی است.',
    retry: 'تلاش دوباره',
    offline: 'اتصال اینترنت برقرار نیست.',
    noMessage: 'پیامی برای ارسال وجود ندارد.',
    connectionError: 'خطا در ارتباط با سرور.',
    receiveError: 'خطا در دریافت پاسخ.',
    emptyReply: 'پاسخی دریافت نشد.',
    unavailable: 'سرویس موقتاً در دسترس نیست. لطفاً بعداً تلاش کنید.',
    chips: [
      'خواب دیدم باران می‌بارد',
      'آب زلال دیدم',
      'دندانم افتاد',
      'خواب مرده دیدم',
      'خواب مار دیدم',
      'در خواب پرواز کردم',
      'نان گرم خوردم',
      'خواب عروسی دیدم',
      'کعبه را در خواب دیدم',
      'خواب ترسناک دیدم چه کنم؟',
    ],
  },
  pashto: {
    title: 'اسلامي خوب تعبیر',
    subtitle: 'د قرآن، حدیث او د اهل سنت کتابونو له مخې',
    notConfigured: 'د خوب تعبیر خدمت لا تر اوسه نه دی برابر شوی.',
    welcome: 'السلام علیکم. خپل خوب په ساده ژبه راته ووایاست — څه مو ولیدل او په خوب کې مو څه احساس درلود؟ ان‌شاءالله د قرآن، حدیث او د اهل سنت معتبرو کتابونو له مخې يې تعبیروم.',
    placeholder: 'خپل خوب دلته ولیکئ…',
    newChat: 'نوې خبرې اترې',
    chipsLabel: 'عام خوبونه:',
    disclaimer: 'د خوب تعبیر ظني دی؛ یقیني پوهه یوازې د الله سبحانه و تعالی سره ده.',
    retry: 'بیا هڅه',
    offline: 'له انټرنېټ سره اړیکه نشته.',
    noMessage: 'د لېږلو لپاره پیغام نشته.',
    connectionError: 'له سرور سره د اړیکې تېروتنه.',
    receiveError: 'د ځواب ترلاسه کولو تېروتنه.',
    emptyReply: 'ځواب ترلاسه نه شو.',
    unavailable: 'خدمت اوس مهال شتون نه لري. مهرباني وکړئ وروسته هڅه وکړئ.',
    chips: [
      'خوب مې ولید چې باران ورېږي',
      'صافه اوبه مې ولیدې',
      'غاښ مې ولوېد',
      'مړی مې په خوب کې ولید',
      'مار مې ولید',
      'په خوب کې الوتلم',
      'تود ډوډۍ مې وخوړ',
      'د واده خوب مې ولید',
      'کعبه مې په خوب کې ولیده',
      'ډارونکی خوب مې ولید، څه وکړم؟',
    ],
  },
  english: {
    title: 'Islamic dream interpretation',
    subtitle: 'Based on the Quran, hadith and Sunni scholarly works',
    notConfigured: 'The dream interpretation service is not configured yet.',
    welcome:
      'As-salamu alaykum. Tell me your dream in plain words — what did you see, and how did you feel in the dream? In sha Allah I will interpret it based on the Quran, hadith and trusted Sunni works.',
    placeholder: 'Write your dream here…',
    newChat: 'New conversation',
    chipsLabel: 'Common dreams:',
    disclaimer: 'Dream interpretation is speculative; certain knowledge belongs to Allah alone.',
    retry: 'Try again',
    offline: 'No internet connection.',
    noMessage: 'There is no message to send.',
    connectionError: 'Could not reach the server.',
    receiveError: 'Could not receive the reply.',
    emptyReply: 'No reply was received.',
    unavailable: 'The service is temporarily unavailable. Please try again later.',
    chips: [
      'I dreamt it was raining',
      'I saw clear water',
      'My tooth fell out',
      'I saw someone who has passed away',
      'I saw a snake',
      'I was flying in my dream',
      'I ate warm bread',
      'I dreamt of a wedding',
      'I saw the Kaaba in my dream',
      'I had a frightening dream, what should I do?',
    ],
  },
  turkish: {
    title: 'İslami rüya tabiri',
    subtitle: 'Kur’an, hadis ve Ehl-i sünnet kitaplarına göre',
    notConfigured: 'Rüya tabiri hizmeti henüz kurulmadı.',
    welcome:
      'Selamün aleyküm. Rüyanızı sade bir dille anlatın — ne gördünüz ve rüyada ne hissettiniz? İnşaallah Kur’an, hadis ve güvenilir Ehl-i sünnet eserlerine göre tabir ederim.',
    placeholder: 'Rüyanızı buraya yazın…',
    newChat: 'Yeni konuşma',
    chipsLabel: 'Sık görülen rüyalar:',
    disclaimer: 'Rüya tabiri zannîdir; kesin bilgi yalnız Allah’a aittir.',
    retry: 'Yeniden dene',
    offline: 'İnternet bağlantısı yok.',
    noMessage: 'Gönderilecek bir mesaj yok.',
    connectionError: 'Sunucuya ulaşılamadı.',
    receiveError: 'Yanıt alınamadı.',
    emptyReply: 'Bir yanıt gelmedi.',
    unavailable: 'Hizmet geçici olarak kapalı. Lütfen sonra tekrar deneyin.',
    chips: [
      'Yağmur yağdığını gördüm',
      'Berrak su gördüm',
      'Dişim düştü',
      'Vefat etmiş birini gördüm',
      'Yılan gördüm',
      'Rüyamda uçuyordum',
      'Sıcak ekmek yedim',
      'Düğün rüyası gördüm',
      'Rüyamda Kâbe’yi gördüm',
      'Korkunç bir rüya gördüm, ne yapayım?',
    ],
  },
  arabic: {
    title: 'تفسير الرؤى الإسلامي',
    subtitle: 'وفق القرآن والحديث وكتب أهل السنة',
    notConfigured: 'خدمة تفسير الرؤى لم تُهيأ بعد.',
    welcome:
      'السلام عليكم. قصّوا رؤياكم بكلام بسيط — ماذا رأيتم وماذا أحسستم في المنام؟ إن شاء الله أفسّرها وفق القرآن والحديث وكتب أهل السنة الموثوقة.',
    placeholder: 'اكتبوا رؤياكم هنا…',
    newChat: 'محادثة جديدة',
    chipsLabel: 'رؤى شائعة:',
    disclaimer: 'تفسير الرؤى ظنّي، والعلم اليقيني عند الله وحده.',
    retry: 'حاولوا مرة أخرى',
    offline: 'لا يوجد اتصال بالإنترنت.',
    noMessage: 'لا توجد رسالة للإرسال.',
    connectionError: 'تعذر الاتصال بالخادم.',
    receiveError: 'تعذر استلام الرد.',
    emptyReply: 'لم يصل رد.',
    unavailable: 'الخدمة غير متاحة مؤقتًا. حاولوا لاحقًا.',
    chips: [
      'رأيت مطرًا ينزل',
      'رأيت ماءً صافيًا',
      'سقطت سنّي',
      'رأيت ميتًا',
      'رأيت حيّة',
      'كنت أطير في المنام',
      'أكلت خبزًا ساخنًا',
      'رأيت حفل زفاف',
      'رأيت الكعبة في المنام',
      'رأيت حلمًا مخيفًا، ماذا أفعل؟',
    ],
  },
} as const;
