export const DREAM_INPUT_MAX_LENGTH = 2000;

export const DREAM_COPY = {
  dari: {
    title: 'تعبیر خواب اسلامی',
    subtitle: 'بر اساس قرآن، حدیث و کتب اهل سنت',
    notConfigured: 'سرویس تعبیر خواب هنوز پیکربندی نشده است.',
    welcome: 'السلام علیکم. خواب خود را به زبان ساده برایم قصه کنید — چه دیدید و در خواب چه احساسی داشتید؟ ان‌شاءالله بر اساس قرآن، حدیث و کتب معتبر اهل سنت برای شما تعبیر می‌کنم.',
    placeholder: 'خواب خود را اینجا بنویسید…',
    newChat: 'گفتگوی جدید',
    chipsLabel: 'خواب‌های عام:',
    note: 'اگر خواب ترسناک بود نگران نشوید؛ خواب پریشان از شیطان است و تعبیر نمی‌شود.',
    disclaimer: 'تعبیر خواب ظنی است؛ علم قطعی تنها نزد الله سبحانه و تعالی است.',
    retry: 'تلاش دوباره',
    offline: 'اتصال اینترنت برقرار نیست.',
    noMessage: 'پیامی برای ارسال وجود ندارد.',
    connectionError: 'خطا در ارتباط با سرور.',
    receiveError: 'خطا در دریافت پاسخ.',
    emptyReply: 'پاسخی دریافت نشد.',
    unavailable: 'سرویس موقتاً در دسترس نیست. لطفاً بعداً تلاش کنید.',
    chips: [
      'خواب دیدم باران می‌بارد',
      'آب زلال دیدم',
      'دندانم افتاد',
      'خواب مرده دیدم',
      'خواب مار دیدم',
      'در خواب پرواز کردم',
      'نان گرم خوردم',
      'خواب عروسی دیدم',
      'کعبه را در خواب دیدم',
      'خواب ترسناک دیدم چه کنم؟',
    ],
  },
  pashto: {
    title: 'اسلامي خوب تعبیر',
    subtitle: 'د قرآن، حدیث او د اهل سنت کتابونو له مخې',
    notConfigured: 'د خوب تعبیر خدمت لا تر اوسه نه دی برابر شوی.',
    welcome: 'السلام علیکم. خپل خوب په ساده ژبه راته ووایاست — څه مو ولیدل او په خوب کې مو څه احساس درلود؟ ان‌شاءالله د قرآن، حدیث او د اهل سنت معتبرو کتابونو له مخې يې تعبیروم.',
    placeholder: 'خپل خوب دلته ولیکئ…',
    newChat: 'نوې خبرې اترې',
    chipsLabel: 'عام خوبونه:',
    note: 'که خوب ډارونکی و، اندېښنه مه کوئ؛ ګډوډ خوب د شیطان له لوري دی او تعبیر نه لري.',
    disclaimer: 'د خوب تعبیر ظني دی؛ یقیني پوهه یوازې د الله سبحانه و تعالی سره ده.',
    retry: 'بیا هڅه',
    offline: 'له انټرنېټ سره اړیکه نشته.',
    noMessage: 'د لېږلو لپاره پیغام نشته.',
    connectionError: 'له سرور سره د اړیکې تېروتنه.',
    receiveError: 'د ځواب ترلاسه کولو تېروتنه.',
    emptyReply: 'ځواب ترلاسه نه شو.',
    unavailable: 'خدمت اوس مهال شتون نه لري. مهرباني وکړئ وروسته هڅه وکړئ.',
    chips: [
      'خوب مې ولید چې باران ورېږي',
      'صافه اوبه مې ولیدې',
      'غاښ مې ولوېد',
      'مړی مې په خوب کې ولید',
      'مار مې ولید',
      'په خوب کې الوتلم',
      'تود ډوډۍ مې وخوړ',
      'د واده خوب مې ولید',
      'کعبه مې په خوب کې ولیده',
      'ډارونکی خوب مې ولید، څه وکړم؟',
    ],
  },
  english: {
    title: 'Islamic dream interpretation',
    subtitle: 'Based on the Quran, hadith and Sunni scholarly works',
    notConfigured: 'The dream interpretation service is not configured yet.',
    welcome:
      'As-salamu alaykum. Tell me your dream in plain words — what did you see, and how did you feel in the dream? In sha Allah I will interpret it based on the Quran, hadith and trusted Sunni works.',
    placeholder: 'Write your dream here…',
    newChat: 'New conversation',
    chipsLabel: 'Common dreams:',
    note: 'If the dream was frightening, do not worry; a disturbing dream is from Shaytan and carries no interpretation.',
    disclaimer: 'Dream interpretation is speculative; certain knowledge belongs to Allah alone.',
    retry: 'Try again',
    offline: 'No internet connection.',
    noMessage: 'There is no message to send.',
    connectionError: 'Could not reach the server.',
    receiveError: 'Could not receive the reply.',
    emptyReply: 'No reply was received.',
    unavailable: 'The service is temporarily unavailable. Please try again later.',
    chips: [
      'I dreamt it was raining',
      'I saw clear water',
      'My tooth fell out',
      'I saw someone who has passed away',
      'I saw a snake',
      'I was flying in my dream',
      'I ate warm bread',
      'I dreamt of a wedding',
      'I saw the Kaaba in my dream',
      'I had a frightening dream, what should I do?',
    ],
  },
} as const;
